apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: team1-namespace1-app1
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./infrastructure/appchart
      sourceRef:
        kind: GitRepository
        name: admin-repository
        namespace: flux-system
      valuesFile: ../environments/dev/values.yaml
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    configVersion: "1.0.3"
    replicaCount: 2
    image: "mcreativo/hello-world"
    appVersion: "1.0.0"
    appName: "hello-world"
    appPort: 5000
    exposedPort: 6000
    namespace: team1-namespace1-app1
    environments:
      dbUrl: db-dev